---
# tasks file for roles/proxy
- name: Run HTTPD
  docker_container:
  # Name of the container, it will also be its hostname for other containers
    name: httpd
    image: raspout/my-httpd:latest
    # Expose the container to the app_network previously created
    networks: 
      - name: app_network
    # Expose only port 80
    ports:
      - "80:80"
    # Start the container
    state: started
    restart_policy: always
    # Pull the image again at each run, otherwise the local "latest" image will be used, which may not be the latest
    pull: true