---
# tasks file for roles/app
- name: Run backend
  docker_container:
    # Name of the container, it will also be its hostname for other containers
    name: backend
    image: raspout/my-backend:latest
    # Expose the container to the app_network previously created
    networks: 
      - name: app_network
    env:
      DB_HOST: "{{ db_host }}"
      DB_PORT: "{{ db_port }}"
      DB_NAME: "{{ db_name }}"
      DB_USERNAME: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
    # Start the container
    state: started
    restart_policy: always
    # Pull the image again at each run, otherwise the local "latest" image will be used, which may not be the latest
    pull: true