---
# tasks file for roles/app
- name: Run backend
  docker_container:
    name: backend
    image: raspout/my-backend:latest
    networks: 
      - name: app_network
    env:
      DB_HOST: "{{ db_host }}"
      DB_PORT: "{{ db_port }}"
      DB_NAME: "{{ db_name }}"
      DB_USERNAME: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
    state: started
    restart_policy: always