all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: ~/.ssh/ssh_priv_key_devops

  children:
    prod:
      hosts: alexis.carella.takima.cloud
      vars:    
        db_password: "VerySecret"
        db_user: "user"
        db_host: "database"
        db_port: "5432"
        db_name: "db"
