---
# tasks file for roles/docker
#Install required packages
  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
      state: latest
  - name: add repo docker
    command: 
      cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: Install docker
    yum:
      name: docker-ce
      state: present

    # Install latest lvm2 
  - name: Install lvm2
    yum:
      name: lvm2
      state: latest

  - name: Install Docker with Python3
    pip:
      name: docker
      executable: pip3
    vars:
      ansible_python_interpreter: /usr/bin/python3

    # Make sure that the docker service is running
  - name: make sur Docker is running
    service:
      name: docker
      state: started
    tags: docker
