- hosts: alexis.carella.takima.cloud
  gather_facts: false
  # Become = execute the tasks as root
  become: true
  # Include the roles
  roles:
    - docker
    - network
    - database
    - app
    - proxy
    - front
