name: CI-deploy
on:
  #to begin you want to launch this job in main and develop
  workflow_run:
    workflows: ["CI-push"]
    types:
      - completed
    branches: 
    - main

jobs:
  # define job to build and publish docker image
  deploy:
   # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    # Environment for the variables
    environment: production
    # only run job if the previous job was successful
    if: github.event.workflow_run.conclusion == 'success'   # steps to perform in job
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      
      - name: Install ansible
        run: sudo apt-get install ansible
    
      - name: prepare ssh key
        run: |
            cd
            mkdir -p ~/.ssh
            echo {{ secrets.ssh_priv_key_devops }} > .ssh/ssh_priv_key_devops
            chmod 600 .ssh/ssh_priv_key_devops

      - name: Deploy to server with ansible
        working-directory: ./tp3-ansible
        run: |
            ansible-playbook -i inventories/setup.yml playbook.yml
    